### ISSUE TITLE
Error in estimating error of (a**x)

### ISSUE THREAD

**Issue by Codeprey** [tisimst/soerp#7]
Hello,
I am trying to estimate the error of a formula, and the code goes to a dead loop. 
After some attempts I find the problem lies in the (a**x) like formula, which belongs to '__rpow__' type.

A simple example for a dead loop is like:
>>> alpha=N(20,1)
>>> 10**alpha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
(984 loops skipped...)
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/soerp/__init__.py", line 426, in __rpow__
    return _make_UF_compatible_object(ADF.__rpow__(self, val))
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 787, in __rpow__
    return to_auto_diff(val)**self
  File "/opt/anaconda3/lib/python3.7/site-packages/ad/__init__.py", line 39, in to_auto_diff
    if isinstance(x, ADF):
RecursionError: maximum recursion depth exceeded while calling a Python object

In soerp/__init__.py:
    def __rpow__(self, val):
        return _make_UF_compatible_object(ADF.__rpow__(self, val))
    
In ad/__init__.py:
    def __rpow__(self,val):
        return to_auto_diff(val)**self

Please solve this problem, thanks!

Sincerely,
Peter

**Comment by Codeprey** [comment]
Also a small fix in soerp/umath/umath.py:

line 163-165:

def pow(x):
    return _make_UF_compatible_object(admath.pow(x))
__all__.append('pow')

It should be
def pow(x,y):
    return _make_UF_compatible_object(admath.pow(x,y))
__all__.append('pow')
